### ISSUE TITLE
[meta] Decide if we want to continue to have to archive websites

### ISSUE THREAD

**Issue by mherchel** [florida-drupalcamp/fldc-d7#8]
Throwing this up on an issue because @ThatGuyCND and I discussed over IRC

---

In previous years we archived websites, and threw them up on 20xx.fldrupal.camp subdomains. 

@jeppy64's data model links everything to one event, so we don't _need_ to do that anymore. But.. do we _want_ to?

Benefits of archiving:
- Old site will retain theme and markup
- It can be archived to static html and thrown up on github pages for free
- Never have to worry about security updates

My thoughts are
- Yeah, we can use Theme Key or something to switch the themes, but that:
  1. Adds complexity
  2. Doesn't guarantee that the _markup_ of previous years' themes will not change (although it should)
- The website will have to be archived eventually anyway. This may be 10 years down the line (after d8 support ends), but still...
- When we make changes down the road, we'll have to regression test all the old "archived" events, which adds a crapload of technical debt.

Examples:
1. We change the ordering of a view, that will change all the older events' views, too.
2. We add a new page or functionality in the future, it will affect the older events

Thoughts on all of this? What are the benefits of throwing all of this into a single data model?

cc @ThatGuyCND @ultimike @jeppy64

**Comment by jeppy64** [comment]
Here's my 2 cents.. kinda,
I actually have two separate D8 Relativity silos for event management. The first and far more elaborate (but still tiny footprint) is a true multi event management system. This one is based on the Group module (not OG). This enables the same entity relation structure but each event has its own independent url alias structure and all related content, users, configs etc all honor that same structure. This lets us have one single site but house and be able to navigate through all (past, present and future) events and not have to archive anything. But I have some blockers in this... the biggest two are Automatic Entity Label module and the Group Menu module. On a lesser blocker note, Rules. With those 3 modules, I could release this probably within a couple of weeks.

Erik had some needs for a smaller single event spin off data model. When we initially talked it made sense to take what I did for the big system and scale it down to handle a single event. This spin off is what I did a demo to Mike Anello with. On this silo, Auto Entity Label is still a blocker, but I can get around it in the UI. This silo is mature and bug free so far and with a front end we could launch this immediately.

On a last thought.. there is no EventBrite integration for D8 that I know of. (it isn't even being talked about from what I know). Then again, I think we SOL due to EventBrite being on their API 2.0 and our custom module built in 2015 was built for API 1.0. (though I could be wrong there).

I'm open to either or and will gladly do what you guys want me to to do. Personally, I think the single event silo is the most reachable because all we really need there is a front end. As for importing EventBrite attendees, I'm sure we could find a way to make that happen even without a true module integration.
